// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


















import type React from "react"
import type { Metadata } from "next"
import { GeistSans } from "geist/font/sans"
import { GeistMono } from "geist/font/mono"
import { Analytics } from "@vercel/analytics/next"
import { Suspense } from "react"
import "./globals.css"
import { Chatbot } from "@/components/chatbot"

export const metadata: Metadata = {
  title: "MLSA - Microsoft Learn Student Ambassadors",
  description:
    "Join our vibrant tech community at Microsoft Learn Student Ambassadors. Discover events, resources, and opportunities to grow your tech skills.",
  generator: "v0.app",
  keywords: ["MLSA", "Microsoft Learn", "Student Ambassadors", "Tech Community", "Programming", "Technology"],
  authors: [{ name: "MLSA Team" }],
  openGraph: {
    title: "MLSA - Microsoft Learn Student Ambassadors",
    description: "Join our vibrant tech community at Microsoft Learn Student Ambassadors",
    type: "website",
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`font-sans ${GeistSans.variable} ${GeistMono.variable} antialiased`}>
        <Suspense fallback={null}>{children}</Suspense>
        <Chatbot />
        <Analytics />
      </body>
    </html>
  )
}
